all:
  vars:
    ansible_user: ansible
    ansible_become: true
    ansible_become_password: "{{ ansible }}"
    ansible_ssh_password: "{{ ansible }}"

  hosts:
    proxmoxve:
      ansible_host: 10.0.0.11
    raspberrypi:
      ansible_host: 10.0.0.12

  children:
    virtual_machines:
      hosts:
        pdocker:
          ansible_host: 10.0.1.1                        
    container:
      hosts:
        ppibound:
          ansible_host: 10.0.2.1
        pnas:
          ansible_host: 10.0.2.2
        pjellyfin:
          ansible_host: 10.0.2.3
        pcolman:
          ansible_host: 10.0.2.4