all:
  vars:
    ansible_user: ansible
    ansible_become: true
    ansible_become_password: "{{ ansible }}"
    ansible_ssh_password: "{{ ansible }}"

  hosts:
    proxmoxve:
      ansible_host: 10.0.0.11
    raspberrypi:
      ansible_host: 10.0.0.12

  children:
    virtual_machines:
      hosts:
        pJellyfin:
          ansible_host: 10.0.1.1      
        pBackup:
          ansible_host: 10.0.1.4                    
    container:
      hosts:
        pPibound:
          ansible_host: 10.0.2.1
        pGrafana:
          ansible_host: 10.0.2.2
        pInfluxDB:
          ansible_host: 10.0.2.3
        pPython3:
          ansible_host: 10.0.2.4
        pFileserver:
          ansible_host: 10.0.2.5
