services:
  watchtower:
    container_name: watchtower
    hostname: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 5 * * *
      - WATCHTOWER_NOTIFICATIONS=gotify
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL={URL}
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=ASjh_pEc_NRToeU
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - home
networks:
  home:
    external: true