version: "3"
services:
  watchtower:
    container_name: watchtower
    hostname: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 5 * * * # check for updates every day
      - WATCHTOWER_NOTIFICATIONS=gotify
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=URL
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=API_KEY
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: bridge
