services:
  gotify:
    image: ghcr.io/gotify/server:latest
    container_name: gotify
    hostname: gotify
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./data:/app/data:rw
    restart: unless-stopped
    depends_on: []
    ports:
      - 5004:80
    networks:
      - home
networks:
  home:
    external: true