services:
  mysql:
    restart: unless-stopped
    image: mysql:8.0
    container_name: mysql
    hostname: dMysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: ${MYSQL_SEMAPHORE_PASSWORD}
      TZ: Europe/Berlin
    networks:
      home:
        ipv4_address: IP_ADDRESS
    dns: DNS_RESOLVER
  semaphore:
    restart: unless-stopped
    image: semaphoreui/semaphore:latest
    container_name: semaphore
    hostname: dSemaphore
    volumes:
      - ./data/semaphore/vault:/etc/ansible/vault:rw
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: ${MYSQL_SEMAPHORE_PASSWORD}
      SEMAPHORE_DB_HOST: 10.10.0.14
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${ENCRYPTION}
      ANSIBLE_HOST_KEY_CHECKING: "false"
      TZ: Europe/Berlin
    depends_on:
      - mysql # for postgres, change to: postgres
    networks:
      home:
        ipv4_address: IP_ADDRESS
    dns: DNS_RESOLVER
networks:
  home:
    external: true