services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    hostname: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Berlin
    volumes:
      - ./data:/app/config:rw
    restart: unless-stopped
    ports:
      - 5010:5055
    networks:
      - home
networks:
  home:
    external: true