- name: Copy authorized_keys
  hosts: all
  vars_files:
    - /etc/ansible/vault/secret.yaml
  tasks:
    - name: Make sure that the .ssh folder exists
      file:
        path: /home/USER/.ssh
        state: directory
        mode: '0755'
        owner: USER
        group: USER
      register: ssh_folder

    - name: Copying authorized_keys
      copy:
        src: /home/USER/.ssh/authorized_keys
        dest: /home/USER/.ssh/authorized_keys
        mode: '0644'
        owner: USER
        group: USER
      when: ssh_folder.changed
