- name: Playbook to Create Ansible user
  hosts: all
  vars_files:
    - /etc/ansible/vault/secret.yaml
  tasks:
    - name: Create ansible user
      user:
        name: USER
        password: PASS
        group: sudo
        createhome: yes
        home: /home/USER
