- name: Playbook to Create users
  hosts: all
  vars_files:
    - /etc/ansible/vault/secret.yaml
  tasks:
    - name: create users group
      group:
        name: USER
        state: present

    - name: Create user
      user:
        name: USER
        password: "password" #must be hashed with mkpasswd
        group: USER
        groups: sudo
        shell: /bin/bash
        createhome: yes
        home: /home/USER
