- name: Playbook to delte users
  hosts: all
  vars_files:
    - /etc/ansible/vault/secret.yaml
  tasks:
    - name: Delete user
      user:
        name: USER 
        state: absent
        remove: true
