- name: Update all packages and check for restart
  hosts: machines
  become: true
  vars_files:
    - /etc/ansible/vault/secret.yaml
  tasks:
    - name: Update the package cache
      apt:
        update_cache: yes

    - name: Install all updates
      apt:
        upgrade: yes
        autoremove: yes
        purge: yes
        autoclean: yes

    - name: Check whether a restart is required
      command: test -f /var/run/reboot-required
      register: reboot_required_result
      changed_when: false
      failed_when: false

    - name: Send message to Gotify if reboot is required
      uri:
        url: "http://192.168.178.74:3004/message?token={{ gotify_key }}"
        method: POST
        body_format: form-urlencoded
        body: "title={{ inventory_hostname }}&message=Reboot required.&priority=5"
      when: reboot_required_result.rc == 0
