- name: Update all packages
  hosts: virtual_machines
  become: true
  vars_files:
    - /etc/ansible/vault/secret.yaml
  tasks:
    - name: Update the package cache (for Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install all updates (for Debian/Ubuntu)
      apt:
        upgrade: yes
        autoremove: yes
        purge: yes
        autoclean: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Update all installed packages to the latest versions (for Alpine)
      community.general.apk:
        upgrade: true
      when: ansible_distribution == 'Alpine'

    - name: Check whether a reboot is required
      command: test -f /var/run/reboot-required
      register: reboot_required_result
      changed_when: false
      failed_when: reboot_required_result.rc == 0

    - name: Send message to Gotify if reboot is required
      uri:
        url: "{{ gotify }}"
        method: POST
        body_format: form-urlencoded
        body: "title={{ inventory_hostname }}&message=Reboot required.&priority=5"
      when: reboot_required_result.rc == 0
