version: "3"
services:
  dozzle:
    hostname: dozzle
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - PORT:8080
    network_mode: bridge
