version: "3.8"
services:
  nginx:
    container_name: npm
    hostname: dNpm
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    volumes:
      - ./data:/data:rw
      - ./letsencrypt:/etc/letsencrypt:rw
    environment: []
    networks:
      home:
        ipv4_address: IP_ADDRESS
    dns: DNS_RESOLVER
    depends_on: []
    ports: []
networks:
  home:
    external: true
