services:
  nginx:
    container_name: npm
    hostname: npm
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    volumes:
      - ./data:/data:rw
      - ./letsencrypt:/etc/letsencrypt:rw
      - ./_hsts_map.conf:/app/templates/_hsts_map.conf
    environment:
      - TZ=Europe/Berlin
    ports:
      - 80:80
      - 443:443
      - 5001:81
    networks:
      - home
networks:
  home:
    external: true