# ITS NOT MY DOCKER COMPOSE
# CREDITS TO: boschkundendienst
# FOR MORE INFOS AND HOW TO USE THIS COMPOSE FILE, VISIT [HIS GITHUB](https://github.com/boschkundendienst/guacamole-docker-compose) 
# THE COMPOSE FILE BELOW IS A LITTLE BIT CUSTOMIZED TO MY NEEDS


version: "2.0"
services:
  guacd:
    container_name: guacd
    hostname: dGuacd
    image: guacamole/guacd
    networks:
      home:
        ipv4_address: IP_ADDRESS
    dns: DNS_RESOLVER
    restart: always
    volumes:
      - ./drive:/drive:rw
      - ./record:/record:rw
  postgres:
    container_name: postgres_guacamole
    hostname: dPostgres
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: ChooseYourOwnPasswordHere1234
      POSTGRES_USER: guacamole_user
    image: postgres:15.2-alpine
    networks:
      home:
        ipv4_address: IP_ADDRESS
    dns: DNS_RESOLVER
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d:z
      - ./data:/var/lib/postgresql/data:Z
  guacamole:
    container_name: guacamole
    hostname: dGuacamole
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: dGuacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
    image: guacamole/guacamole
    networks:
      home:
        ipv4_address: IP_ADRESS
    dns: DNS_RESOLVER
    links:
      - guacd
    restart: always
networks:
  home:
    external: true
