services:
  organizr:
    container_name: organizr
    hostname: organizr
    image: organizr/organizr
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - fpm=true
    volumes:
      - ./data:/config:rw
    ports:
      - 5011:80
    networks:
      - home
networks:
  home:
    external: true