services:
  dockge:
    container_name: dockge
    hostname: dockge
    image: louislam/dockge:latest
    restart: unless-stopped
    ports:
      - 5002:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /opt/stacks:/opt/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/opt/stacks
    networks:
      - home
networks:
  home:
    external: true