version: "3.8"
services:
  dockge:
    container_name: dockge
    hostname: dockge
    image: louislam/dockge:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /opt/stacks:/opt/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/opt/stacks
    networks:
      home:
        ipv4_address: IP_ADDRESS
    dns:
      DNS_RESOLVER
networks:
  home:
    external: true
