version: "3.3"
services:
  barcodebuddy:
    container_name: barcodebuddy
    hostname: barcodebuddy
    volumes:
      - ./data:/config
    image: f0rc3/barcodebuddy:latest
    environment:
      - TZ=Europe/Berlin
    ports:
      - 5008:80
    networks:
      - home
networks:
  home:
    external: true