version: "3.3"
services:
  server:
    container_name: vaultwarden
    hostname: dVaultwarden
    volumes:
      - ./data:/data/:rw
    restart: unless-stopped
    image: vaultwarden/server:latest
    ports: []
    environment:
      - TZ=Europe/Berlin
    networks:
      home:
        ipv4_address: IP_ADDRESS
    dns: DNS_RESOLVER
    depends_on: []
networks:
  home:
    external: true
