services:
  server:
    container_name: vaultwarden
    hostname: vaultwarden
    volumes:
      - ./data:/data/:rw
    restart: unless-stopped
    image: vaultwarden/server:latest
    environment:
      - TZ=Europe/Berlin
    ports:
      - 5003:80
    networks:
      - home
networks:
  home:
    external: true